# Dependencies
#markdown:         redcarpet
#highlighter:      pygments

# Permalinks
permalink:        /:categories/:title/
#relative_permalinks: true

# Setup
title:            Rolando +4
tagline:          'O Podcast dos Carrascos dos Mestres'
description:      'Esse é o podcast que vai ensinar você a combar, apelar, maximizar e criar personagens épicos para aventuras épicas!'
url:              http://rolandomaisquatro.github.io/
baseurl:          /

author:
  name:           'Fábio Emilio Costa'
  url:            https://twitter.com/hufflepuffbr

paginate:         10

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

collections:
  authors:
    output: true
